### PR TITLE
Destinations: Webhooks - start tests.

### PR DESCRIPTION
**Pull request by cpursley**
Happy path start to tests. Trying [bypass](https://github.com/PSPDFKit-labs/bypass) library but glad to use [mimic](https://github.com/edgurgel/mimic) or something else.

### CODE REVIEW

**Comment by cpursley** [comment]
@themusicman any idea why I'm getting this sort of thing error:

```
 [error] Argument error for event: %ArgumentError{message: "cannot change belongs_to association `destination` because there is already a change setting its foreign key `destination_id` to `\"91770803-448c-4242-ab8b-b82a9899c700\"`"}
```

Which I'm able to get around by commenting this line out: https://github.com/eventrelay/eventrelay/pull/68/files#diff-8b09af21077646f99baf7f69c6b53682600a80f74566de380dd037b933a42419R115

**Comment by cpursley** [comment]
Also, what are your thoughts on these webhook server tests?: https://github.com/eventrelay/eventrelay/blob/fe2a7b12ad583edc9278a7f2b7e1a69b96f80160/test/event_relay/destinations/delivery/webhook/server_test.exs

Seems to work okay. I'd like to test various cases. Let me know what ideas you have.

**Comment by cpursley** [comment]
Also, I think this was a bug ("id" in function head): https://github.com/eventrelay/eventrelay/pull/68/files#diff-8b09af21077646f99baf7f69c6b53682600a80f74566de380dd037b933a42419L94

**Comment by themusicman** [comment]
> Also, I think this was a bug ("id" in function head): https://github.com/eventrelay/eventrelay/pull/68/files#diff-8b09af21077646f99baf7f69c6b53682600a80f74566de380dd037b933a42419L94

All the genservers that `use ER.Server`  have an `id` in the state and it is the id of the resource they are associated with. In this case a delivery.

**Comment by themusicman** [comment]
> Also, what are your thoughts on these webhook server tests?: https://github.com/eventrelay/eventrelay/blob/fe2a7b12ad583edc9278a7f2b7e1a69b96f80160/test/event_relay/destinations/delivery/webhook/server_test.exs
> 
> I'd like to test various situations (slow or overloaded server, request limit hit, etc). Let me know what ideas you have.

I like where you are going here. As a stylistic thing I would drop the `_of_affairs`. 

In terms of testing things related to performance I think we should tag those and run them on a PR merge. This way they are only run occasionally and not all the time as they will probably greatly increase the time to run the test suite. If we run them on the merge of a PR they could block a PR from being merged but not bloat the time for normally test runs.

**Comment by cpursley** [comment]
@themusicman I'm struggling to follow how all this works. I added the "id" back to the handlers and added some inline logging. Please check the CI run to see where/how things fail. If you have time maybe we could meet and you could walk me through or you could comment in-line on the changes (obviously not today).

**Comment by themusicman** [comment]
> @themusicman I'm struggling to follow how all this works. I added the "id" back to the handlers and added some inline logging. Please check the CI run to see where/how things fail. If you have time maybe we could meet and you could walk me through or you could comment in-line on the changes (obviously not today).

Something is causing two different destinations to be at play here. First you have the one that is already set for the delivery:
```
destination: %ER.Destinations.Destination{
                   __meta__: #Ecto.Schema.Metadata<:loaded, "destinations">,
                   id: "f3b448e7-53b3-4eb4-9917-e3870178c134",
```
Then there is the destination that being set again later:

```
"create_delivery_for_event 1"
[
  attrs: %{
    status: :success,
    attempts: [
      %{
        "attempted_at" => ~U[2023-12-25 20:01:33.213389Z],
        "response" => %{
          headers: %{
            "CACHE-CONTROL" => "max-age=0, private, must-revalidate",
            "CONTENT-LENGTH" => "366",
            "DATE" => "Mon, 25 Dec 2023 20:01:33 GMT",
            "SERVER" => "Cowboy"
          },
          status_code: 200
        }
      }
    ],
    destination_id: "4cb645bf-65df-4f1f-93fa-b668d631f759",
    event_id: "9521c3d9-777f-448e-b5ee-4cf7048c7e81"
  }
]
```

Not sure yet where the second destination is coming from.

**Pull request closed without merging**
